# Generated by Django 4.2.8 on 2023-12-14 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=140)),
                ('title_banner', models.ImageField(blank=True, default='', null=True, upload_to='title_banner')),
                ('summery', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_day', models.DateField(null=True)),
                ('frequency', models.CharField(choices=[('주 1일', 1), ('주 2일', 2), ('주 3일', 3), ('주 4일', 4), ('주 5일', 5), ('주 6일', 6), ('주 7일', 7), ('평일 매일', 8), ('주말 매일', 9)], default='', max_length=50)),
                ('duration', models.CharField(choices=[('1주 동안', 1), ('2주 동안', 2), ('3주 동안', 3), ('4주 동안', 4)], max_length=50, null=True)),
                ('start_time', models.CharField(blank=True, default='', max_length=30)),
                ('end_time', models.CharField(blank=True, default='', max_length=30)),
                ('notice', models.TextField(blank=True)),
                ('max_member', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20)])),
                ('number_of_applied_member', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
