# Generated by Django 4.2.8 on 2023-12-14 02:39

import challenge.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_my_certifications_profile_my_challenges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0003_challengeapply_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='certifications',
            field=models.ManyToManyField(related_name='Certifications', to='challenge.certification'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='member',
            field=models.ManyToManyField(through='challenge.ChallengeApply', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PhotoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=challenge.models.upload_to_certi_photo_example)),
                ('type', models.CharField(choices=[(0, 'success'), (1, 'fail')], default='', max_length=50)),
                ('challenge_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_example_challenge', to='challenge.challenge', verbose_name='challenge name')),
                ('owner', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
