# Generated by Django 5.0 on 2024-01-03 07:58

import challenge.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0003_challengeapply_certification"),
        ("user", "0007_alter_user_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="created",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="modified",
        ),
        migrations.AddField(
            model_name="challenge",
            name="certifications",
            field=models.ManyToManyField(
                related_name="challenge_certifications",
                through="challenge.Certification",
                to="user.profile",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="member",
            field=models.ManyToManyField(
                related_name="challenge_apply",
                through="challenge.ChallengeApply",
                to="user.profile",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
