# Generated by Django 4.2.8 on 2023-12-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challenge_certifications_challenge_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='certifications',
            field=models.ManyToManyField(default='', related_name='Certifications', to='challenge.certification'),
        ),
    ]
