# Generated by Django 5.0 on 2024-01-03 08:29

import challenge.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0004_remove_certification_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="certifications",
        ),
        migrations.AddField(
            model_name="challenge",
            name="certifications",
            field=models.ManyToManyField(
                related_name="challenge_certifications", to="challenge.certification"
            ),
        ),
        migrations.CreateModel(
            name="PhotoExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=challenge.models.upload_to_certi_photo_example,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[(0, "success"), (1, "fail")], default="", max_length=50
                    ),
                ),
                (
                    "challenge_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_example_challenge",
                        to="challenge.challenge",
                        verbose_name="challenge name",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
        ),
    ]
