# Generated by Django 5.0 on 2024-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_challenge_certifications_photoexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='certifications',
            field=models.ManyToManyField(blank=True, default='', related_name='challenge_certifications', to='challenge.certification'),
        ),
    ]
