# Generated by Django 5.0 on 2024-01-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_challenge_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certification_photo',
            field=models.FileField(blank=True, default='', null=True, upload_to='certification'),
        ),
    ]
