# Generated by Django 5.0 on 2024-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_alter_certification_certification_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='max_member',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='PhotoExample',
        ),
    ]
