# Generated by Django 5.0 on 2024-03-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_remove_challenge_frequency_and_more'),
        ('user', '0010_alter_profile_my_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='max_member',
            new_name='max_hour',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='member',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='number_of_applied_member',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='challengeapply',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengeapply',
            name='user',
        ),
        migrations.AddField(
            model_name='challenge',
            name='certifications_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.profile'),
        ),
    ]
