# Generated by Django 5.0 on 2024-05-08 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_alter_challenge_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='challenge',
            new_name='challenge_id',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='user',
            new_name='user_profile_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_comment',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_photo',
        ),
        migrations.AddField(
            model_name='certification',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='certifications',
            field=models.ManyToManyField(blank=True, default='', related_name='challenge_certification', to='challenge.certification'),
        ),
        migrations.CreateModel(
            name='CertificationInfo',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('num', models.IntegerField(default=1)),
                ('certification_date', models.DateTimeField(auto_now=True)),
                ('certification_photo', models.FileField(blank=True, default='', null=True, upload_to='certification')),
                ('certification_local_photo_url', models.TextField(blank=True)),
                ('certification_comment', models.CharField(blank=True, max_length=255)),
                ('certification_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_Info', to='challenge.certification')),
            ],
        ),
    ]
