# Generated by Django 5.0 on 2024-04-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_alter_challenge_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='challenge',
            new_name='challenge_id',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='user',
            new_name='user_profile_id',
        ),
    ]
