# Generated by Django 5.0 on 2024-05-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_rename_challenge_certification_challenge_id_and_more'),
        ('user', '0020_alter_user_nickname_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='challenge_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='user_profile_id',
        ),
        migrations.RemoveField(
            model_name='certificationinfo',
            name='certification_comment',
        ),
        migrations.RemoveField(
            model_name='certificationinfo',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='certificationinfo',
            name='certification_id',
        ),
        migrations.RemoveField(
            model_name='certificationinfo',
            name='certification_local_photo_url',
        ),
        migrations.RemoveField(
            model_name='certificationinfo',
            name='certification_photo',
        ),
        migrations.RemoveField(
            model_name='certificationinfo',
            name='num',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_Info', to='challenge.certification'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_local_photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_photo',
            field=models.FileField(blank=True, default='', null=True, upload_to='certification'),
        ),
        migrations.AddField(
            model_name='certification',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='certificationinfo',
            name='challenge_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_challenge', to='challenge.challenge', verbose_name='challenge name'),
        ),
        migrations.AddField(
            model_name='certificationinfo',
            name='user_profile_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_profile', to='user.profile', verbose_name='member name'),
        ),
    ]
