# Generated by Django 5.0 on 2024-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_remove_certification_challenge_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='num',
        ),
        migrations.AddField(
            model_name='certification',
            name='certification_num',
            field=models.IntegerField(default=0),
        ),
    ]
