# Generated by Django 5.0 on 2024-05-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_remove_certification_num_and_more'),
        ('user', '0020_alter_user_nickname_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certification_comment',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_local_photo_url',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_num',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='certification_photo',
        ),
        migrations.AddField(
            model_name='certification',
            name='challenge_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_challenge', to='challenge.challenge', verbose_name='challenge name'),
        ),
        migrations.AddField(
            model_name='certification',
            name='user_profile_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_profile', to='user.profile', verbose_name='member name'),
        ),
        migrations.CreateModel(
            name='CertificationDetail',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('certification_num', models.IntegerField(default=0)),
                ('certification_date', models.DateTimeField(auto_now=True)),
                ('certification_photo', models.FileField(blank=True, default='', null=True, upload_to='certification')),
                ('certification_local_photo_url', models.TextField(blank=True)),
                ('certification_comment', models.CharField(blank=True, max_length=255)),
                ('certification_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='challenge.certification')),
            ],
        ),
        migrations.DeleteModel(
            name='CertificationInfo',
        ),
    ]
