# Generated by Django 5.0 on 2024-05-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_remove_certification_certification_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationdetail',
            name='certification_num',
            field=models.IntegerField(),
        ),
    ]
