# Generated by Django 5.0 on 2024-05-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_alter_certification_id_alter_certificationdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationdetail',
            name='certification_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certification_detail', to='challenge.certification'),
        ),
    ]
