# Generated by Django 5.0 on 2024-06-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_certification_certification_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='certification_comment',
            new_name='certification_dairy',
        ),
    ]
