# Generated by Django 5.0.6 on 2024-06-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenge",
            "0019_rename_certification_comment_certification_certification_dairy",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="certification_local_photo_url",
        ),
    ]
