# Generated by Django 5.0.6 on 2024-06-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0020_remove_certification_certification_local_photo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certification",
            old_name="certification_dairy",
            new_name="certification_diary",
        ),
    ]
