# Generated by Django 5.0.6 on 2024-06-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenge",
            "0021_rename_certification_dairy_certification_certification_diary",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certification_photo",
            field=models.FileField(blank=True, default="", upload_to="certification"),
        ),
    ]
