# Generated by Django 5.0 on 2023-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_my_certifications_profile_my_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(2, 'client'), (1, 'company_client'), (0, 'admin')], default=2, verbose_name='사용자 레벨(client=1,admin=0)'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
