# Generated by Django 5.0 on 2023-12-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(choices=[(1, 'client'), (0, 'admin')], default=1, verbose_name='사용자 레벨(client=1,admin=0)'),
        ),
    ]
