# Generated by Django 5.0 on 2024-01-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenge", "0005_alter_challenge_certifications_photoexample"),
        ("user", "0007_alter_user_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="my_certifications",
        ),
        migrations.AddField(
            model_name="profile",
            name="my_certifications",
            field=models.ManyToManyField(
                related_name="profile_certifications", to="challenge.certification"
            ),
        ),
    ]
