# Generated by Django 5.0 on 2024-03-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_openchallenge_rename_max_member_challenge_max_hour_and_more'),
        ('user', '0010_alter_profile_my_certifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_challenges',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_challenges',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
        ),
    ]
