# Generated by Django 5.0 on 2024-03-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_openchallenge_rename_max_member_challenge_max_hour_and_more'),
        ('user', '0013_alter_profile_my_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_challenges',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
        ),
    ]
