# Generated by Django 5.0 on 2024-03-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_alter_challenge_owner'),
        ('user', '0014_alter_profile_my_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_challenges',
        ),
        migrations.AddField(
            model_name='profile',
            name='my_challenges',
            field=models.ManyToManyField(blank=True, default='', null=True, to='challenge.challenge'),
        ),
    ]
