# Generated by Django 5.0 on 2024-03-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profile_my_challenges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='my_challenges',
            new_name='my_closed_challenges',
        ),
    ]
