# Generated by Django 5.0 on 2024-03-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_profile_nickname_alter_user_nickname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname_id',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.profile'),
        ),
    ]
